export const metadata = {
    title: "About Next.js",
    description: "Generated by Next.js",
  };
export default function Page() {
    return (
        <main>
            <h1 className="text-3xl font-bold underline">About</h1>
        </main>
    );
}