import React from 'react';
import { Metadata } from 'next';

export const metadata = {
    title: {
        absolute: "",
        default: "Next.js Tutorial- First Blog",
        template: "%s| Next.js",
    },
    description: "Generated by Next.js",
};  
export default function FirstBlog() {
    return (
        <main>
            <h1 className="text-3xl font-bold underline">First Blog</h1>
        </main>
    );
}