export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <header style={{ padding: "1em", textAlign: "center", background: "lightblue"}}>
                <p>Header</p>
                    <nav>
                        {/* Add navigation links here */}
                    </nav>
                    
                </header>
                {children}

                <footer style={{ padding: "1em", background: "ghostwhite", textAlign: "center"}}>
                    <p>Footer</p>
                    <p>&copy; {new Date().getFullYear()} My App</p>
                </footer>
            </body>
        </html>
    );
}